ERROR - 2022-11-10 00:17:18 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('127.0.0.1', 'root', '', 'ci4', 3307, '', 0)
#1 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('alfan', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('username', 'username', 'alfan', Array, Array)
#7 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\SIGudang_Obat-main\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\SIGudang_Obat-main\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('alfan', 'username', Array, NULL, 'username')
#5 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('username', 'username', 'alfan', Array, Array)
#6 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\SIGudang_Obat-main\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptRegister()
#9 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\SIGudang_Obat-main\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-11-10 00:17:18 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('alfan', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('username', 'username', 'alfan', [...], [...])
 6 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 00:39:51 --> hash(): Unknown hashing algorithm: alfn2008
in VENDORPATH\myth\auth\src\Password.php on line 63.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'hash(): Unknown hashing algorithm: alfn2008', 'VENDORPATH\\myth\\auth\\src\\Password.php', 63, [...])
 2 VENDORPATH\myth\auth\src\Password.php(63): hash('alfn2008', 'gudangobat', true)
 3 VENDORPATH\myth\auth\src\Password.php(33): Myth\Auth\Password::preparePassword('gudangobat')
 4 VENDORPATH\myth\auth\src\Entities\User.php(63): Myth\Auth\Password::hash('gudangobat')
 5 SYSTEMPATH\Entity\Entity.php(451): Myth\Auth\Entities\User->setPassword('gudangobat')
 6 SYSTEMPATH\Entity\Entity.php(138): CodeIgniter\Entity\Entity->__set('password', 'gudangobat')
 7 SYSTEMPATH\Entity\Entity.php(119): CodeIgniter\Entity\Entity->fill([...])
 8 VENDORPATH\myth\auth\src\Authentication\Passwords\ValidationRules.php(66): CodeIgniter\Entity\Entity->__construct([...])
 9 VENDORPATH\myth\auth\src\Authentication\Passwords\ValidationRules.php(39): Myth\Auth\Authentication\Passwords\ValidationRules->buildUserFromRequest()
10 SYSTEMPATH\Validation\Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('gudangobat', null)
11 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('password', 'password', 'gudangobat', [...], [...])
12 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
13 VENDORPATH\myth\auth\src\Controllers\AuthController.php(164): CodeIgniter\Controller->validate([...])
14 SYSTEMPATH\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptRegister()
15 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
16 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 00:40:34 --> hash(): Unknown hashing algorithm: alf200
in VENDORPATH\myth\auth\src\Password.php on line 63.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'hash(): Unknown hashing algorithm: alf200', 'VENDORPATH\\myth\\auth\\src\\Password.php', 63, [...])
 2 VENDORPATH\myth\auth\src\Password.php(63): hash('alf200', 'gudangobat', true)
 3 VENDORPATH\myth\auth\src\Password.php(33): Myth\Auth\Password::preparePassword('gudangobat')
 4 VENDORPATH\myth\auth\src\Entities\User.php(63): Myth\Auth\Password::hash('gudangobat')
 5 SYSTEMPATH\Entity\Entity.php(451): Myth\Auth\Entities\User->setPassword('gudangobat')
 6 SYSTEMPATH\Entity\Entity.php(138): CodeIgniter\Entity\Entity->__set('password', 'gudangobat')
 7 SYSTEMPATH\Entity\Entity.php(119): CodeIgniter\Entity\Entity->fill([...])
 8 VENDORPATH\myth\auth\src\Authentication\Passwords\ValidationRules.php(66): CodeIgniter\Entity\Entity->__construct([...])
 9 VENDORPATH\myth\auth\src\Authentication\Passwords\ValidationRules.php(39): Myth\Auth\Authentication\Passwords\ValidationRules->buildUserFromRequest()
10 SYSTEMPATH\Validation\Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('gudangobat', null)
11 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('password', 'password', 'gudangobat', [...], [...])
12 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
13 VENDORPATH\myth\auth\src\Controllers\AuthController.php(164): CodeIgniter\Controller->validate([...])
14 SYSTEMPATH\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptRegister()
15 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
16 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 00:40:46 --> hash(): Unknown hashing algorithm: she384
in VENDORPATH\myth\auth\src\Password.php on line 63.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'hash(): Unknown hashing algorithm: she384', 'VENDORPATH\\myth\\auth\\src\\Password.php', 63, [...])
 2 VENDORPATH\myth\auth\src\Password.php(63): hash('she384', 'gudangobat', true)
 3 VENDORPATH\myth\auth\src\Password.php(33): Myth\Auth\Password::preparePassword('gudangobat')
 4 VENDORPATH\myth\auth\src\Entities\User.php(63): Myth\Auth\Password::hash('gudangobat')
 5 SYSTEMPATH\Entity\Entity.php(451): Myth\Auth\Entities\User->setPassword('gudangobat')
 6 SYSTEMPATH\Entity\Entity.php(138): CodeIgniter\Entity\Entity->__set('password', 'gudangobat')
 7 SYSTEMPATH\Entity\Entity.php(119): CodeIgniter\Entity\Entity->fill([...])
 8 VENDORPATH\myth\auth\src\Authentication\Passwords\ValidationRules.php(66): CodeIgniter\Entity\Entity->__construct([...])
 9 VENDORPATH\myth\auth\src\Authentication\Passwords\ValidationRules.php(39): Myth\Auth\Authentication\Passwords\ValidationRules->buildUserFromRequest()
10 SYSTEMPATH\Validation\Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('gudangobat', null)
11 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('password', 'password', 'gudangobat', [...], [...])
12 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
13 VENDORPATH\myth\auth\src\Controllers\AuthController.php(164): CodeIgniter\Controller->validate([...])
14 SYSTEMPATH\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptRegister()
15 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
16 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 00:41:56 --> hash(): Unknown hashing algorithm: alfn2008
in VENDORPATH\myth\auth\src\Password.php on line 63.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'hash(): Unknown hashing algorithm: alfn2008', 'VENDORPATH\\myth\\auth\\src\\Password.php', 63, [...])
 2 VENDORPATH\myth\auth\src\Password.php(63): hash('alfn2008', 'gudangobat', true)
 3 VENDORPATH\myth\auth\src\Password.php(33): Myth\Auth\Password::preparePassword('gudangobat')
 4 VENDORPATH\myth\auth\src\Entities\User.php(63): Myth\Auth\Password::hash('gudangobat')
 5 SYSTEMPATH\Entity\Entity.php(451): Myth\Auth\Entities\User->setPassword('gudangobat')
 6 SYSTEMPATH\Entity\Entity.php(138): CodeIgniter\Entity\Entity->__set('password', 'gudangobat')
 7 SYSTEMPATH\Entity\Entity.php(119): CodeIgniter\Entity\Entity->fill([...])
 8 VENDORPATH\myth\auth\src\Authentication\Passwords\ValidationRules.php(66): CodeIgniter\Entity\Entity->__construct([...])
 9 VENDORPATH\myth\auth\src\Authentication\Passwords\ValidationRules.php(39): Myth\Auth\Authentication\Passwords\ValidationRules->buildUserFromRequest()
10 SYSTEMPATH\Validation\Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('gudangobat', null)
11 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('password', 'password', 'gudangobat', [...], [...])
12 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
13 VENDORPATH\myth\auth\src\Controllers\AuthController.php(164): CodeIgniter\Controller->validate([...])
14 SYSTEMPATH\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptRegister()
15 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
16 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 01:05:31 --> Cannot redeclare Myth\Auth\Config\Auth::$personalFields
in VENDORPATH\myth\auth\src\Config\Auth.php on line 127.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2022-11-10 01:06:26 --> Class name must be a valid object or a string
in VENDORPATH\myth\auth\src\Config\Services.php on line 81.
 1 SYSTEMPATH\Config\BaseService.php(253): Myth\Auth\Config\Services::activator(Object(Myth\Auth\Config\Auth), false)
 2 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('activator', [...])
 3 VENDORPATH\myth\auth\src\Config\Services.php(74): CodeIgniter\Config\BaseService::getSharedInstance('activator', null)
 4 SYSTEMPATH\Config\BaseService.php(253): Myth\Auth\Config\Services::activator()
 5 SYSTEMPATH\Common.php(959): CodeIgniter\Config\BaseService::__callStatic('activator', [])
 6 VENDORPATH\myth\auth\src\Controllers\AuthController.php(184): service('activator')
 7 SYSTEMPATH\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptRegister()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-10 01:17:23 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Email\Email.php:1730
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1730, Array)
#1 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Email\Email.php(1730): mail('s21910113@stude...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Thu, 10 N...', '-f 21910113@stu...')
#2 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\SIGudang_Obat-main\vendor\myth\auth\src\Authentication\Activators\EmailActivator.php(32): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\SIGudang_Obat-main\vendor\myth\auth\src\Controllers\AuthController.php(185): Myth\Auth\Authentication\Activators\EmailActivator->send(Object(Myth\Auth\Entities\User))
#6 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SIGudang_Obat-main\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SIGudang_Obat-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
ERROR - 2022-11-10 01:17:23 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2022-11-10 01:17:23 --> 
CRITICAL - 2022-11-10 01:54:00 --> Class name must be a valid object or a string
in VENDORPATH\myth\auth\src\Config\Services.php on line 81.
 1 SYSTEMPATH\Config\BaseService.php(253): Myth\Auth\Config\Services::activator(Object(Myth\Auth\Config\Auth), false)
 2 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('activator', [...])
 3 VENDORPATH\myth\auth\src\Config\Services.php(74): CodeIgniter\Config\BaseService::getSharedInstance('activator', null)
 4 SYSTEMPATH\Config\BaseService.php(253): Myth\Auth\Config\Services::activator()
 5 SYSTEMPATH\Common.php(959): CodeIgniter\Config\BaseService::__callStatic('activator', [])
 6 VENDORPATH\myth\auth\src\Controllers\AuthController.php(184): service('activator')
 7 SYSTEMPATH\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptRegister()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-10 02:00:30 --> Invalid file: user/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('user/index', [], true)
 3 APPPATH\Controllers\User.php(9): view('user/index')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
